image: Visual Studio 2019

environment:
  global:
    BITS: 32
  matrix:
    - CONFIGURATION: Release
      COMPILER: MinGW
      PLATFORM: i686
    - CONFIGURATION: Release
      COMPILER: MinGW
      PLATFORM: x86_64

build:
  verbosity: detailed

install:
- ps: |
    if ($env:PLATFORM -eq "x86_64") {
      $env:BITS = 64
    }

build_script:
- ps: |
    $APPVEYOR_LOGGER = "C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll";
    switch ($env:COMPILER) {
      MSVC {
        msbuild rufus.sln /m /p:Configuration=$env:CONFIGURATION,Platform=$env:PLATFORM /l:$APPVEYOR_LOGGER;
      }
      MinGW {
         bash -lc "export PATH=/mingw$env:BITS/bin:`$PATH; cd /c/projects/AppVeyor; ls /; ls /c; gcc -o test test.c";
      }
    }
